Schema.intersect([
    Schema.object({
        interrogator_model: Schema.union(["cl_tagger_1_01", "wd-convnext-v3", "wd-swinv2-v3", "wd-vit-v3", "wd14-convnextv2-v2", "wd14-swinv2-v2", "wd14-vit-v2", "wd14-moat-v2", "wd-eva02-large-tagger-v3", "wd-vit-large-tagger-v3", "eva02_large_E621_FULL_V1", "llm-openai", "llm-claude", "llm-custom"]).default("wd14-convnextv2-v2").description("Tagger 模型 / LLM 模式"),
        path: Schema.string().role('folder').required().description("图片文件夹路径"),
        threshold: Schema.number().role("slider").min(0).max(1).step(0.01).default(0.35).description("阈值"),
        character_threshold: Schema.number().role("slider").min(0).max(1).step(0.01).default(0.6).description("角色名称识别阈值（仅 cl_tagger 生效）"),
        add_rating_tag: Schema.boolean().default(false).description("添加等级标签"),
        add_model_tag: Schema.boolean().default(false).description("添加 AI 模型标签"),
        additional_tags: Schema.string().description("附加提示词 (逗号分隔)"),
        exclude_tags: Schema.string().description("排除标签 (逗号分隔)"),
        replace_underscore: Schema.boolean().default(true).description("使用空格代替下划线"),
        escape_tag: Schema.boolean().default(true).description("将结果中的括号进行转义处理"),
        batch_input_recursive: Schema.boolean().default(false).description("递归搜索子文件夹图片"),
        batch_output_action_on_conflict: Schema.union(["ignore", "copy", "prepend", "append"]).default("ignore").description("若已经存在识别的 Tag 文件，则"),
        create_backup_before_write: Schema.boolean().default(false).description("覆盖前先创建 caption 备份"),
        backup_snapshot_name: Schema.string().description("备份名称（留空自动生成）"),
    }).description("Tagger 参数设置"),
    Schema.object({
        llm_api_base: Schema.string().default("").description("LLM API Base URL。OpenAI 兼容默认 `https://api.openai.com/v1`，Claude 兼容默认 `https://api.anthropic.com/v1`。也可填写自定义兼容端点"),
        llm_api_style: Schema.union(["openai-compatible", "claude-compatible"]).default("openai-compatible").description("自定义 API 协议类型。仅 `llm-custom` 模式需要关心"),
        llm_api_key: Schema.string().default("").description("LLM API Key。注意：LLM 模式会把缩放后的图片发送到你填写的远程 API"),
        llm_model: Schema.string().default("").description("LLM 模型名称。留空无法启动 LLM 标注"),
        llm_template_preset: Schema.union(["anime-tags", "natural-caption", "json-caption"]).default("anime-tags").description("LLM 模板预设：动漫标签 / 自然语言描述 / JSON 打标"),
        llm_output_mode: Schema.union(["auto", "tags", "raw_text"]).default("auto").description("LLM 输出模式。`auto` 会跟随当前预设推荐值"),
        llm_temperature: Schema.number().role("slider").min(0).max(2).step(0.05).default(0.2).description("LLM temperature"),
        llm_max_tokens: Schema.number().default(300).description("LLM 最大输出 token"),
        llm_timeout: Schema.number().default(120).description("LLM 请求超时秒数"),
        llm_system_prompt: Schema.string().role("textarea").default("").description("LLM 系统提示词。留空时自动使用当前预设内置提示词"),
        llm_user_template: Schema.string().role("textarea").default("").description("LLM 自定义模板。留空时自动使用当前预设内置模板。可用占位符：`{filename}` `{stem}` `{relative_path}` `{absolute_path}` `{existing_caption}`"),
    }).description("LLM 模式（OpenAI / Claude 兼容）"),
])
